"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import { AuthModalProvider } from "./components/context/AuthModalContext";
import AuthenticationModal from "./components/AuthenticationModal";
import { useAuthModal } from "./components/context/AuthModalContext";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <AuthModalProvider>
          {children} <AuthenticationModalWrapper />
        </AuthModalProvider>
      </body>
    </html>
  );
}

function AuthenticationModalWrapper() {
  const { isAuthOpen, closeAuthModal } = useAuthModal();
  return <AuthenticationModal isOpen={isAuthOpen} onClose={closeAuthModal} />;
}
