"use client"
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AuthModalProvider } from "./components/context/AuthModalContext";
import AuthenticationModal from "./components/AuthenticationModal";
import { AuthProvider } from "./components/context/AuthContext";
import { Provider } from "react-redux";
import { store } from "./redux/store";
import AppWrapper from "./components/wrappers/AppWrapper";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "advancedVI",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Provider store={store}>
          <AuthProvider>
            <AuthModalProvider>
              <AppWrapper>
                {children}
                <AuthenticationModal />
              </AppWrapper>
            </AuthModalProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
