
import { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/app/clients/ClientProviders";

const roboto = Roboto({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Summarist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
       <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
